#!/bin/sh
#cp ../../clean/include/
# ./ocpninclude/.

cp ../../clean/src/bbox.cpp ./ocpnsrc/.
cp ../../clean/src/cutil.cpp ./ocpnsrc/.
cp ../../clean/src/geodesic.cpp ./ocpnsrc/.
cp ../../clean/src/georef.cpp ./ocpnsrc/.
cp ../../clean/src/Hyperlink.cpp ./ocpnsrc/.
cp ../../clean/src/Layer.cpp ./ocpnsrc/.
cp ../../clean/src/ocpndc.cpp ./ocpnsrc/.
cp ../../clean/src/pugixml.cpp ./ocpnsrc/.
cp ../../clean/src/SelectItem.cpp ./ocpnsrc/.

cp ../../clean/include/AISTargetAlertDialog.h ./ocpninclude/.
cp ../../clean/include/AISTargetQueryDialog.h ./ocpninclude/.
cp ../../clean/src/nmea0183/apb.hpp ./ocpninclude/.
cp ../../clean/include/bbox.h ./ocpninclude/.
cp ../../clean/include/canvasMenu.h ./ocpninclude/.
cp ../../clean/include/chart1.h ./ocpninclude/.
cp ../../clean/include/chartbarwin.h ./ocpninclude/.
cp ../../clean/include/chartbase.h ./ocpninclude/.
cp ../../clean/include/chartdbs.h ./ocpninclude/.
cp ../../clean/include/chartimg.h ./ocpninclude/.
cp ../../clean/include/chcanv.h ./ocpninclude/.
cp ../../clean/include/CM93DSlide.h ./ocpninclude/.
cp ../../clean/include/ConnectionParams.h ./ocpninclude/.
cp ../../clean/include/cutil.h ./ocpninclude/.
cp ../../clean/include/datastream.h ./ocpninclude/.
cp ../../clean/include/dsPortType.h ./ocpninclude/.
cp ../../clean/include/dychart.h ./ocpninclude/.
cp ../../clean/include/emboss_data.h ./ocpninclude/.
cp ../../clean/include/geodesic.h ./ocpninclude/.
cp ../../clean/include/georef.h ./ocpninclude/.
cp ../../clean/src/nmea0183/gga.hpp ./ocpninclude/.
cp ../../clean/src/nmea0183/gll.hpp ./ocpninclude/.
cp ../../clean/include/GoToPositionDialog.h ./ocpninclude/.
cp ../../clean/src/nmea0183/GPwpl.hpp ./ocpninclude/.
cp ../../clean/include/gpxdocument.h ./ocpninclude/.
cp ../../clean/src/nmea0183/gsv.hpp ./ocpninclude/.
cp ../../clean/src/nmea0183/hdg.hpp ./ocpninclude/.
cp ../../clean/src/nmea0183/hdm.hpp ./ocpninclude/.
cp ../../clean/src/nmea0183/hdt.hpp ./ocpninclude/.
cp ../../clean/include/Hyperlink.h ./ocpninclude/.
cp ../../clean/include/IDX_entry.h ./ocpninclude/.
cp ../../clean/src/nmea0183/LatLong.hpp ./ocpninclude/.
cp ../../clean/include/Layer.h ./ocpninclude/.
cp ../../clean/include/LinkPropDlg.h ./ocpninclude/.
cp ../../clean/include/LLRegion.h ./ocpninclude/.
cp ../../clean/include/MarkIcon.h ./ocpninclude/.
cp ../../clean/include/navutil.h ./ocpninclude/.
cp ../../clean/src/nmea0183/nmea0183.h ./ocpninclude/.
cp ../../clean/src/nmea0183/nmea0183.hpp ./ocpninclude/.
cp ../../clean/include/ocpCursor.h ./ocpninclude/.
cp ../../clean/include/ocpndc.h ./ocpninclude/.
cp ../../clean/include/OCPNPlatform.h ./ocpninclude/.
cp ../../clean/include/ocpn_plugin.h ./ocpninclude/.
cp ../../clean/include/OCPNRegion.h ./ocpninclude/.
cp ../../clean/include/ocpn_types.h ./ocpninclude/.
cp ../../clean/include/pluginmanager.h ./ocpninclude/.
cp ../../clean/include/pugiconfig.hpp ./ocpninclude/.
cp ../../clean/include/pugixml.hpp ./ocpninclude/.
cp ../../clean/include/Quilt.h ./ocpninclude/.
cp ../../clean/src/nmea0183/Response.hpp ./ocpninclude/.
cp ../../clean/src/nmea0183/RMB.hpp ./ocpninclude/.
cp ../../clean/src/nmea0183/RMC.HPP ./ocpninclude/.
cp ../../clean/include/RolloverWin.h ./ocpninclude/.
cp ../../clean/include/Route.h ./ocpninclude/.
cp ../../clean/include/RoutePoint.h ./ocpninclude/.
cp ../../clean/include/routeprop.h ./ocpninclude/.
cp ../../clean/src/nmea0183/rte.hpp ./ocpninclude/.
cp ../../clean/include/s52s57.h ./ocpninclude/.
cp ../../clean/include/s57chart.h ./ocpninclude/.
cp ../../clean/include/S57ClassRegistrar.h ./ocpninclude/.
cp ../../clean/include/S57Light.h ./ocpninclude/.
cp ../../clean/include/S57QueryDialog.h ./ocpninclude/.
cp ../../clean/include/s57RegistrarMgr.h ./ocpninclude/.
cp ../../clean/include/S57Sector.h ./ocpninclude/.
cp ../../clean/include/scrollingdialog.h ./ocpninclude/.
cp ../../clean/include/SelectItem.h ./ocpninclude/.
cp ../../clean/src/nmea0183/Sentence.hpp ./ocpninclude/.
cp ../../clean/include/styles.h ./ocpninclude/.
cp ../../clean/include/TexFont.h ./ocpninclude/.
cp ../../clean/include/timers.h ./ocpninclude/.
cp ../../clean/include/undo.h ./ocpninclude/.
cp ../../clean/include/vector2D.h ./ocpninclude/.
cp ../../clean/include/viewport.h ./ocpninclude/.
cp ../../clean/src/nmea0183/vtg.hpp ./ocpninclude/.
cp ../../clean/src/nmea0183/wpl.hpp ./ocpninclude/.
cp ../../clean/include/wx28compat.h ./ocpninclude/.
cp ../../clean/src/nmea0183/xte.hpp ./ocpninclude/.

cp -R ../../clean/src/wxcurl/include ./ocpninclude/wxcurl/.
cp -R ../../clean/src/wxcurl/wx ./ocpninclude/wxcurl/.

cp ../../clean/src/wxsvg/include/wxSVG/* ./ocpninclude/wxsvg/.

cp ../../clean/src/wxsvg/include/wxSVGXML/svgxml.h ./ocpninclude/wxSVGXML/.
