# -*- rpm-spec -*-
BuildRoot:      /home/jon/opencpn/odraw/build-kde18/_CPack_Packages/Linux/RPM/ocpn_draw_pi_1.4.71-1_amd64
Summary:        ocpn_draw_pi PlugIn for OpenCPN
Name:           ocpn_draw_pi
Version:        1.4.71
Release:        1
License:        gplv3+
Group:          unknown
Vendor:         opencpn.org

Requires: opencpn, bzip2, gzip











Prefix: /usr


%define _rpmdir /home/jon/opencpn/odraw/build-kde18/_CPack_Packages/Linux/RPM
%define _rpmfilename ocpn_draw_pi_1.4.71-1_amd64.rpm
%define _unpackaged_files_terminate_build 0
%define _topdir /home/jon/opencpn/odraw/build-kde18/_CPack_Packages/Linux/RPM


%define _binary_payload w7.xzdio

%description
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.



# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT "/home/jon/opencpn/odraw/build-kde18/_CPack_Packages/Linux/RPM/tmpBBroot"

#p build

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv "/home/jon/opencpn/odraw/build-kde18/_CPack_Packages/Linux/RPM/tmpBBroot" $RPM_BUILD_ROOT

%clean

%post

#!/bin/sh
/bin/cp -R /usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons /home/$SUDO_USER/.opencpn/plugins/ocpn_draw_pi/.
/bin/rm -Rf /usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons
/bin/echo "Copied user icons"



%postun


%pre


%preun


%files
%defattr(-,root,root,-)
%dir "/usr/lib/opencpn"
%dir "/usr/share/locale"
%dir "/usr/share/locale/ar_SA"
%dir "/usr/share/locale/ar_SA/LC_MESSAGES"
"/usr/share/locale/ar_SA/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/ca_ES"
%dir "/usr/share/locale/ca_ES/LC_MESSAGES"
"/usr/share/locale/ca_ES/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/cs_CZ"
%dir "/usr/share/locale/cs_CZ/LC_MESSAGES"
"/usr/share/locale/cs_CZ/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/da_DK"
%dir "/usr/share/locale/da_DK/LC_MESSAGES"
"/usr/share/locale/da_DK/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/de_DE"
%dir "/usr/share/locale/de_DE/LC_MESSAGES"
"/usr/share/locale/de_DE/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/el_GR"
%dir "/usr/share/locale/el_GR/LC_MESSAGES"
"/usr/share/locale/el_GR/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/es_ES"
%dir "/usr/share/locale/es_ES/LC_MESSAGES"
"/usr/share/locale/es_ES/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/et_EE"
%dir "/usr/share/locale/et_EE/LC_MESSAGES"
"/usr/share/locale/et_EE/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/fi_FI"
%dir "/usr/share/locale/fi_FI/LC_MESSAGES"
"/usr/share/locale/fi_FI/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/fil_PH"
%dir "/usr/share/locale/fil_PH/LC_MESSAGES"
"/usr/share/locale/fil_PH/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/fr_FR"
%dir "/usr/share/locale/fr_FR/LC_MESSAGES"
"/usr/share/locale/fr_FR/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/gl_ES"
%dir "/usr/share/locale/gl_ES/LC_MESSAGES"
"/usr/share/locale/gl_ES/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/hi_IN"
%dir "/usr/share/locale/hi_IN/LC_MESSAGES"
"/usr/share/locale/hi_IN/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/hu_HU"
%dir "/usr/share/locale/hu_HU/LC_MESSAGES"
"/usr/share/locale/hu_HU/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/id_ID"
%dir "/usr/share/locale/id_ID/LC_MESSAGES"
"/usr/share/locale/id_ID/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/it_IT"
%dir "/usr/share/locale/it_IT/LC_MESSAGES"
"/usr/share/locale/it_IT/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/ja_JP"
%dir "/usr/share/locale/ja_JP/LC_MESSAGES"
"/usr/share/locale/ja_JP/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/mr_IN"
%dir "/usr/share/locale/mr_IN/LC_MESSAGES"
"/usr/share/locale/mr_IN/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/nb_NO"
%dir "/usr/share/locale/nb_NO/LC_MESSAGES"
"/usr/share/locale/nb_NO/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/nl_NL"
%dir "/usr/share/locale/nl_NL/LC_MESSAGES"
"/usr/share/locale/nl_NL/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/pl_PL"
%dir "/usr/share/locale/pl_PL/LC_MESSAGES"
"/usr/share/locale/pl_PL/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/pt_BR"
%dir "/usr/share/locale/pt_BR/LC_MESSAGES"
"/usr/share/locale/pt_BR/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/pt_PT"
%dir "/usr/share/locale/pt_PT/LC_MESSAGES"
"/usr/share/locale/pt_PT/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/ro_RO"
%dir "/usr/share/locale/ro_RO/LC_MESSAGES"
"/usr/share/locale/ro_RO/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/ru_RU"
%dir "/usr/share/locale/ru_RU/LC_MESSAGES"
"/usr/share/locale/ru_RU/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/sv_SE"
%dir "/usr/share/locale/sv_SE/LC_MESSAGES"
"/usr/share/locale/sv_SE/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/th_TH"
%dir "/usr/share/locale/th_TH/LC_MESSAGES"
"/usr/share/locale/th_TH/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/tr_TR"
%dir "/usr/share/locale/tr_TR/LC_MESSAGES"
"/usr/share/locale/tr_TR/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/vi_VN"
%dir "/usr/share/locale/vi_VN/LC_MESSAGES"
"/usr/share/locale/vi_VN/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/locale/zh_TW"
%dir "/usr/share/locale/zh_TW/LC_MESSAGES"
"/usr/share/locale/zh_TW/LC_MESSAGES/opencpn-ocpn_draw_pi.mo"
%dir "/usr/share/opencpn"
%dir "/usr/share/opencpn/plugins"
%dir "/usr/share/opencpn/plugins/ocpn_draw_pi"
%dir "/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Anchor-Danger.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Anchor-Safe.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Arrow-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Arrow-Blue.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Arrow-Green.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Arrow-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Authority-Customs.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Authority-Health.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Authority-Immigration.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Authority-Police.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Buoy-Type-A.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Buoy-Type-B.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Circle-Black-On-White.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Circle-Black-On-Yellow.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Circle-Red-On-White.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Circle-White-On-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Circle-White-On-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Circle-Yellow-On-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Diamond-Black-On-White.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Diamond-Black-On-Yellow.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Diamond-Red-On-White.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Diamond-White-On-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Diamond-White-On-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Diamond-Yellow-On-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Diving-Scuba.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Diving-Snorkel.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Diving-Spearing.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Eddies-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Eddies-Blue.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Eddies-Green.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Eddies-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Exclamation-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Exclamation-Blue.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Exclamation-Green.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Exclamation-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Fish-Fishing-Spot.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Fish-Pelagic.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Fish-Reef.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Fish-Shark.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Fish-Whale.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Hazard-Danger.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Hazard-Lighthouse.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Hazard-Obstruction.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Hazard-Rocks-Exposed.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Hazard-Rocks-Submerged.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Hazard-Windfarm.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Hazard-Wreck.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Info-Info.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Info-Photo.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Info-Video.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Light-Green.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Light-Red-Green.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Light-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/MOB-Man-Over-Board.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Cardinal-East-Lighted.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Cardinal-East.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Cardinal-North-Lighted.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Cardinal-North.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Cardinal-South-Lighted.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Cardinal-South.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Cardinal-West-Lighted.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Cardinal-West.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Lateral-Port-Hand-ILALA-A-Lighted.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Lateral-Port-Hand-ILALA-A.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Lateral-Port-Hand-ILALA-B-Lighted.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Lateral-Port-Hand-ILALA-B.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Lateral-Starboard-Hand-ILALA-A-Lighted.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Lateral-Starboard-Hand-ILALA-A.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Lateral-Starboard-ILALA-B-Lighted.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Lateral-Starboard-ILALA-B.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Topmark-Danger-Lighted.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Marks-Topmark-Danger.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Pin-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Pin-Blue.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Pin-Green.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Pin-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Question-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Question-Blue.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Question-Green.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Question-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/README.txt"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Sea-Floor-Clay.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Sea-Floor-Coral.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Sea-Floor-Grass.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Sea-Floor-Mud.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Sea-Floor-Rock.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Sea-Floor-Sand.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Square-Black-On-White.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Square-Black-On-Yellow.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Square-Red-On-White.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Square-White-On-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Square-White-On-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Square-Yellow-On-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Supply-Diesel.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Supply-Food-Drink.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Supply-Gas.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Supply-Internet-Cafe.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Supply-Petrol.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Supply-Repairs.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Supply-Shopping.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Supply-Water.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Supply-WiFi.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Tick-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Tick-Blue.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Tick-Green.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Tick-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Triangle-Black-On-White.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Triangle-Black-On-Yellow.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Triangle-Red-On-White.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Triangle-White-On-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Triangle-White-On-Red.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/Triangle-Yellow-On-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/X-Black.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/X-Blue.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/X-Green.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/UserIcons/X-Red.png"
%dir "/usr/share/opencpn/plugins/ocpn_draw_pi/data"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/DR.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/DR.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/DRgrey.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/DRgrey.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/EBL.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/EBL.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/EBLgrey.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/EBLgrey.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/GZ.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/GZ.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/GZgrey.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/GZgrey.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/ODManager.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/ODManager.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/ODManagerGrey.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/ODManagergrey.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/PIL.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/PIL.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/PILgrey.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/PILgrey.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/boundary.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/boundary.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/boundarygrey.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/boundarygrey.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/license.txt"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/pointbutton.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/pointbutton.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/pointbuttongrey.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/pointbuttongrey.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/textpointbutton.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/textpointbutton.svg"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/textpointbuttongrey.png"
"/usr/share/opencpn/plugins/ocpn_draw_pi/data/textpointbuttongrey.svg"

%config "/usr/lib/opencpn/libocpn_draw_pi.so"



%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 1.4.71-1
  Generated by CPack RPM (no Changelog file were provided)
