/* Autogenerated by png2wx.pl on Thu Nov  4 13:06:52 2010 */
#ifndef OCPNDRAWICONS_H
#define OCPNDRAWICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

extern void initialize_images(void);

extern void *g_ppimgr;
extern wxBitmap *_img_ocpn_draw_pi;
extern wxBitmap *_img_ocpn_draw_gray_pi;
extern wxBitmap *_img_ocpn_draw;
extern wxBitmap *_img_ocpn_draw_boundary;
extern wxBitmap *_img_ocpn_draw_boundary_gray;
extern wxBitmap *_img_ocpn_draw_point;
extern wxBitmap *_img_ocpn_draw_point_gray;
extern const wxBitmap *_img_Bullet_green;
extern const wxBitmap *_img_Bullet_red;
extern const wxBitmap *_img_Bullet_yellow;
#endif /* OCPNDRAWICONS_H */
