#ifndef __ODDRDialogImpl__
#define __ODDRDialogImpl__

/**
@file
Subclass of MyDialogDR, which is generated by wxFormBuilder.
*/

#include "ODDRDialogDef.h"

//// end generated include

/** Implementing MyDialogDR */
class ODDRDialogImpl : public MyDialogDR
{
	protected:
		// Handlers for MyDialogDR events.
		void OnOK( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		/** Constructor */
		ODDRDialogImpl( wxWindow* parent );
	//// end generated class members
	
};

#endif // __ODDRDialogImpl__
